### PR TITLE
Rebuild jinja2-time 0.2.0 for python 3.10 support

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/hackebrot/jinja2-time/releases
License: https://github.com/hackebrot/jinja2-time/blob/0.2.0/LICENSE
Requirements: https://github.com/hackebrot/jinja2-time/blob/0.2.0/setup.py

Actions:
1. Add 0000-replace-replace-shift.patch
2. Bump build number to 3
3. Add (m2)-patch
4. Add missing wheel
5. Remove pinning for arrow
6. Add imports
7. Update tests
8. Add license_family
9. Add license_file

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
We need to update arrow to 1.2.2 https://github.com/AnacondaRecipes/arrow-feedstock/pull/5

**Comment by skupr-anaconda** [comment]
`dateparser `(a test dependency for `arrow`) requires `tzlocal `but it's currently not available on `s390x`

**Comment by skupr-anaconda** [comment]
`arrow `updated to v1.2.2

**Review by varlackc — COMMENTED** [review]
The package looks good but there are a few things that we need to consider

`We should verify the build number`
https://github.com/AnacondaRecipes/jinja2-time-feedstock/blob/rebuild_py310/recipe/meta.yaml#L19

if possible we should add a `dev_url` and `doc_url`
https://github.com/AnacondaRecipes/jinja2-time-feedstock/blob/rebuild_py310/recipe/meta.yaml#L49&&L53

`dev_url`
https://github.com/hackebrot/jinja2-time

`potential doc_url`
https://github.com/hackebrot/jinja2-time/blob/main/README.rst

**Comment by skupr-anaconda** [comment]
> The package looks good but there are a few things that we need to consider
> 
> `We should verify the build number` https://github.com/AnacondaRecipes/jinja2-time-feedstock/blob/rebuild_py310/recipe/meta.yaml#L19
> 
> if possible we should add a `dev_url` and `doc_url` https://github.com/AnacondaRecipes/jinja2-time-feedstock/blob/rebuild_py310/recipe/meta.yaml#L49&&L53
> 
> `dev_url` https://github.com/hackebrot/jinja2-time
> 
> `potential doc_url` https://github.com/hackebrot/jinja2-time/blob/main/README.rst

The previous build number was 2 so now I bump it to 3.
I've added doc and dev uls.

**Review by tobijk — APPROVED** [review]

**Pull request merged**
